# Generated by Django 4.2.30 on 2026-08-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('role', models.CharField(blank=True, max_length=55, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee', models.OneToOneField(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_profile', serialize=False, to='clinic.person')),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('employment_day', models.DateField()),
                ('department', models.ForeignKey(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.department')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('complete', 'Complete'), ('canceled', 'Canceled')], max_length=10, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.department')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor', models.OneToOneField(db_column='DoctorID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to='clinic.employee')),
                ('speciality', models.CharField(max_length=50)),
                ('available_day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse', models.OneToOneField(db_column='NurseID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nurse_profile', serialize=False, to='clinic.employee')),
                ('license_num', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient', models.OneToOneField(db_column='PatientID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to='clinic.person')),
                ('blood_type', models.CharField(max_length=3)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('pending', 'Pending')], max_length=10, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.appointment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergies', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('prescription', models.CharField(blank=True, max_length=50, null=True)),
                ('hereditary_diseases', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.patient')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head_doctor',
            field=models.ForeignKey(blank=True, db_column='HeadDoctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to='clinic.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
        ),
    ]
