# Generated by Django 4.2.30 on 2026-08-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_employee_checked_in_at_employee_is_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
