from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('doctor/patient/<int:patient_id>/', views.doctor_patient_detail, name='doctor_patient_detail'),
    path('admin-panel/create-account/', views.create_account, name='create_account'),
    path('staff/doctors/', views.admin_doctor_list, name='admin_doctor_list'),
    path('staff/doctors/<int:doctor_id>/edit/', views.edit_doctor, name='edit_doctor'),
    path('staff/doctors/<int:doctor_id>/delete/', views.delete_doctor, name='delete_doctor'),
    path('staff/nurses/', views.admin_nurse_list, name='admin_nurse_list'),
    path('staff/nurses/<int:nurse_id>/edit/', views.edit_nurse, name='edit_nurse'),    path('staff/nurses/<int:nurse_id>/delete/', views.delete_nurse, name='delete_nurse'),
    path('staff/departments/', views.admin_department_list, name='admin_department_list'),
    path('staff/departments/<int:department_id>/', views.department_detail, name='department_detail'),
    path('staff/departments/<int:department_id>/remove-member/<int:employee_id>/', views.remove_department_member, name='remove_department_member'),
    path('staff/departments/visit-stats/', views.department_visit_stats, name='department_visit_stats'),
    path('staff/appointments/', views.admin_appointment_list, name='admin_appointment_list'),
    path('staff/appointments/<int:appointment_id>/', views.appointment_detail, name='appointment_detail'),
    path('checkin/', views.toggle_checkin, name='toggle_checkin'),
    path('staff/medical-records/', views.admin_medical_record_list, name='admin_medical_record_list'),
    path('staff/medical-records/<int:record_id>/', views.admin_medical_record_detail, name='admin_medical_record_detail'),
    path('staff/billing/', views.admin_billing_list, name='admin_billing_list'),
    path('staff/employees/', views.admin_employee_list, name='admin_employee_list'),
    path('nurse/patients/', views.nurse_patient_list, name='nurse_patient_list'),
    path('nurse/patients/<int:patient_id>/', views.nurse_patient_detail, name='nurse_patient_detail'),
    path('nurse/patients/add/', views.nurse_add_patient, name='nurse_add_patient'),
    path('staff/sick-leaves/', views.admin_sick_leave_list, name='admin_sick_leave_list'),
    path('sick-leave/', views.request_sick_leave, name='request_sick_leave'),
    path('doctor/patient/<int:patient_id>/vaccinations/', views.doctor_patient_vaccinations, name='doctor_patient_vaccinations'), 
    path('doctor/patient/<int:patient_id>/referrals/', views.doctor_patient_referrals, name='doctor_patient_referrals'), 
    path('doctor/patient/<int:patient_id>/treatment-plans/', views.doctor_patient_treatment_plans, name='doctor_patient_treatment_plans'), 
]